services:
  app:
    container_name: mahjong-score-calculator
    image: oscarhkli/mahjong-score-calculator
    platform: linux/amd64
    ports:
      - "61001:8080"
    env_file:
      - .env # Load variables from .env file
