name: msc
services:
  mahjong-score-calculator:
    container_name: mahjong-score-calculator
    image: oscarhkli/mahjong-score-calculator
    platform: linux/amd64
    ports:
      - "127.0.0.1:8080:8080"
    logging:
      driver: awslogs
      options:
        awslogs-group: msc-backend-logs
        awslogs-stream: msc-logs
    restart: always
