spring:
  application:
    name: mahjong-score-calculator

auth:
  username: ${AUTH_USERNAME}
  password: ${AUTH_PASSWORD}
  token-role: ROLE_USER
  role: USER
  secret-key: ${AUTH_SECRET_KEY}
  token-expiration-minute: 15
  refresh-token-expiration-minute: 1440
logging:
  include-application-name: false
  pattern:
    correlation: ""
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"

---
spring:
  config:
    activate:
      on-profile: default

server:
  port: 60001
  ssl:
    enabled: true
    key-store: ${KEY_STORE_PATH}/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    protocol: TLS
    key-alias: localdev

---
spring:
  config:
    activate:
      on-profile: cloud

server:
  port: 8080
  ssl:
    enabled: true
    key-store: ${KEY_STORE_PATH}/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    protocol: TLS
    key-alias: localdev